services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.web.address=:80
      - --providers.docker.network=sec-ca2_frontend
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend

  webapp:
    build: ./apps/webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      - "traefik.http.services.webapp.loadbalancer.server.port=5000"
      - "traefik.docker.network=sec-ca2_frontend"
    networks:
      - frontend
      - backend

  internal-api:
    image: traefik/whoami
    networks:
      - backend

networks:
  frontend:
  backend:
